# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='language',
            new_name='languageFk',
        ),
    ]
