# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160827_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='languageFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='home.Language'),
        ),
    ]
