# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160827_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='languageFk',
        ),
        migrations.AddField(
            model_name='function',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Language'),
            preserve_default=False,
        ),
    ]
